// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseMsgProto.proto
// Protobuf Java Version: 4.26.0

package com.vanky.chat.common.protobuf;

public final class BaseMsgProto {
  private BaseMsgProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      BaseMsgProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.vanky.chat.common.protobuf.BaseMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>int64 unique_id = 2;</code>
     * @return The uniqueId.
     */
    long getUniqueId();

    /**
     * <code>int64 from_user_id = 3;</code>
     * @return The fromUserId.
     */
    long getFromUserId();

    /**
     * <code>int64 to_user_id = 4;</code>
     * @return The toUserId.
     */
    long getToUserId();

    /**
     * <code>int64 create_time = 5;</code>
     * @return The createTime.
     */
    long getCreateTime();

    /**
     * <code>int32 chat_type = 6;</code>
     * @return The chatType.
     */
    int getChatType();

    /**
     * <code>bytes content = 7;</code>
     * @return The content.
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <code>int32 msg_type = 8;</code>
     * @return The msgType.
     */
    int getMsgType();

    /**
     * <code>int32 status = 9;</code>
     * @return The status.
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code com.vanky.chat.common.protobuf.BaseMsg}
   */
  public static final class BaseMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.vanky.chat.common.protobuf.BaseMsg)
      BaseMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "",
        BaseMsg.class.getName());
    }
    // Use BaseMsg.newBuilder() to construct.
    private BaseMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BaseMsg() {
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vanky.chat.common.protobuf.BaseMsgProto.internal_static_com_vanky_chat_common_protobuf_BaseMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vanky.chat.common.protobuf.BaseMsgProto.internal_static_com_vanky_chat_common_protobuf_BaseMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg.class, com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int UNIQUE_ID_FIELD_NUMBER = 2;
    private long uniqueId_ = 0L;
    /**
     * <code>int64 unique_id = 2;</code>
     * @return The uniqueId.
     */
    @java.lang.Override
    public long getUniqueId() {
      return uniqueId_;
    }

    public static final int FROM_USER_ID_FIELD_NUMBER = 3;
    private long fromUserId_ = 0L;
    /**
     * <code>int64 from_user_id = 3;</code>
     * @return The fromUserId.
     */
    @java.lang.Override
    public long getFromUserId() {
      return fromUserId_;
    }

    public static final int TO_USER_ID_FIELD_NUMBER = 4;
    private long toUserId_ = 0L;
    /**
     * <code>int64 to_user_id = 4;</code>
     * @return The toUserId.
     */
    @java.lang.Override
    public long getToUserId() {
      return toUserId_;
    }

    public static final int CREATE_TIME_FIELD_NUMBER = 5;
    private long createTime_ = 0L;
    /**
     * <code>int64 create_time = 5;</code>
     * @return The createTime.
     */
    @java.lang.Override
    public long getCreateTime() {
      return createTime_;
    }

    public static final int CHAT_TYPE_FIELD_NUMBER = 6;
    private int chatType_ = 0;
    /**
     * <code>int32 chat_type = 6;</code>
     * @return The chatType.
     */
    @java.lang.Override
    public int getChatType() {
      return chatType_;
    }

    public static final int CONTENT_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes content = 7;</code>
     * @return The content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 8;
    private int msgType_ = 0;
    /**
     * <code>int32 msg_type = 8;</code>
     * @return The msgType.
     */
    @java.lang.Override
    public int getMsgType() {
      return msgType_;
    }

    public static final int STATUS_FIELD_NUMBER = 9;
    private int status_ = 0;
    /**
     * <code>int32 status = 9;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (uniqueId_ != 0L) {
        output.writeInt64(2, uniqueId_);
      }
      if (fromUserId_ != 0L) {
        output.writeInt64(3, fromUserId_);
      }
      if (toUserId_ != 0L) {
        output.writeInt64(4, toUserId_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(5, createTime_);
      }
      if (chatType_ != 0) {
        output.writeInt32(6, chatType_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(7, content_);
      }
      if (msgType_ != 0) {
        output.writeInt32(8, msgType_);
      }
      if (status_ != 0) {
        output.writeInt32(9, status_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (uniqueId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, uniqueId_);
      }
      if (fromUserId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, fromUserId_);
      }
      if (toUserId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, toUserId_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, createTime_);
      }
      if (chatType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, chatType_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, content_);
      }
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, msgType_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg)) {
        return super.equals(obj);
      }
      com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg other = (com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg) obj;

      if (getId()
          != other.getId()) return false;
      if (getUniqueId()
          != other.getUniqueId()) return false;
      if (getFromUserId()
          != other.getFromUserId()) return false;
      if (getToUserId()
          != other.getToUserId()) return false;
      if (getCreateTime()
          != other.getCreateTime()) return false;
      if (getChatType()
          != other.getChatType()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getMsgType()
          != other.getMsgType()) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + UNIQUE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUniqueId());
      hash = (37 * hash) + FROM_USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFromUserId());
      hash = (37 * hash) + TO_USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getToUserId());
      hash = (37 * hash) + CREATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + CHAT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getChatType();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.vanky.chat.common.protobuf.BaseMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.vanky.chat.common.protobuf.BaseMsg)
        com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vanky.chat.common.protobuf.BaseMsgProto.internal_static_com_vanky_chat_common_protobuf_BaseMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vanky.chat.common.protobuf.BaseMsgProto.internal_static_com_vanky_chat_common_protobuf_BaseMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg.class, com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg.Builder.class);
      }

      // Construct using com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        uniqueId_ = 0L;
        fromUserId_ = 0L;
        toUserId_ = 0L;
        createTime_ = 0L;
        chatType_ = 0;
        content_ = com.google.protobuf.ByteString.EMPTY;
        msgType_ = 0;
        status_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vanky.chat.common.protobuf.BaseMsgProto.internal_static_com_vanky_chat_common_protobuf_BaseMsg_descriptor;
      }

      @java.lang.Override
      public com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg getDefaultInstanceForType() {
        return com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg build() {
        com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg buildPartial() {
        com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg result = new com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.uniqueId_ = uniqueId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.fromUserId_ = fromUserId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.toUserId_ = toUserId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.createTime_ = createTime_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.chatType_ = chatType_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.msgType_ = msgType_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.status_ = status_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg) {
          return mergeFrom((com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg other) {
        if (other == com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getUniqueId() != 0L) {
          setUniqueId(other.getUniqueId());
        }
        if (other.getFromUserId() != 0L) {
          setFromUserId(other.getFromUserId());
        }
        if (other.getToUserId() != 0L) {
          setToUserId(other.getToUserId());
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.getChatType() != 0) {
          setChatType(other.getChatType());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                uniqueId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                fromUserId_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                toUserId_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                createTime_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                chatType_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 58: {
                content_ = input.readBytes();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 64: {
                msgType_ = input.readInt32();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                status_ = input.readInt32();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long uniqueId_ ;
      /**
       * <code>int64 unique_id = 2;</code>
       * @return The uniqueId.
       */
      @java.lang.Override
      public long getUniqueId() {
        return uniqueId_;
      }
      /**
       * <code>int64 unique_id = 2;</code>
       * @param value The uniqueId to set.
       * @return This builder for chaining.
       */
      public Builder setUniqueId(long value) {

        uniqueId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 unique_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUniqueId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uniqueId_ = 0L;
        onChanged();
        return this;
      }

      private long fromUserId_ ;
      /**
       * <code>int64 from_user_id = 3;</code>
       * @return The fromUserId.
       */
      @java.lang.Override
      public long getFromUserId() {
        return fromUserId_;
      }
      /**
       * <code>int64 from_user_id = 3;</code>
       * @param value The fromUserId to set.
       * @return This builder for chaining.
       */
      public Builder setFromUserId(long value) {

        fromUserId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 from_user_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fromUserId_ = 0L;
        onChanged();
        return this;
      }

      private long toUserId_ ;
      /**
       * <code>int64 to_user_id = 4;</code>
       * @return The toUserId.
       */
      @java.lang.Override
      public long getToUserId() {
        return toUserId_;
      }
      /**
       * <code>int64 to_user_id = 4;</code>
       * @param value The toUserId to set.
       * @return This builder for chaining.
       */
      public Builder setToUserId(long value) {

        toUserId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 to_user_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearToUserId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        toUserId_ = 0L;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>int64 create_time = 5;</code>
       * @return The createTime.
       */
      @java.lang.Override
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>int64 create_time = 5;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(long value) {

        createTime_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int64 create_time = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private int chatType_ ;
      /**
       * <code>int32 chat_type = 6;</code>
       * @return The chatType.
       */
      @java.lang.Override
      public int getChatType() {
        return chatType_;
      }
      /**
       * <code>int32 chat_type = 6;</code>
       * @param value The chatType to set.
       * @return This builder for chaining.
       */
      public Builder setChatType(int value) {

        chatType_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chat_type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        chatType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 7;</code>
       * @return The content.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 7;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000040);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <code>int32 msg_type = 8;</code>
       * @return The msgType.
       */
      @java.lang.Override
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>int32 msg_type = 8;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(int value) {

        msgType_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>int32 msg_type = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 9;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 9;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {

        status_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000100);
        status_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.vanky.chat.common.protobuf.BaseMsg)
    }

    // @@protoc_insertion_point(class_scope:com.vanky.chat.common.protobuf.BaseMsg)
    private static final com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg();
    }

    public static com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseMsg>
        PARSER = new com.google.protobuf.AbstractParser<BaseMsg>() {
      @java.lang.Override
      public BaseMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BaseMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.vanky.chat.common.protobuf.BaseMsgProto.BaseMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_vanky_chat_common_protobuf_BaseMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_vanky_chat_common_protobuf_BaseMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022BaseMsgProto.proto\022\036com.vanky.chat.com" +
      "mon.protobuf\"\255\001\n\007BaseMsg\022\n\n\002id\030\001 \001(\003\022\021\n\t" +
      "unique_id\030\002 \001(\003\022\024\n\014from_user_id\030\003 \001(\003\022\022\n" +
      "\nto_user_id\030\004 \001(\003\022\023\n\013create_time\030\005 \001(\003\022\021" +
      "\n\tchat_type\030\006 \001(\005\022\017\n\007content\030\007 \001(\014\022\020\n\010ms" +
      "g_type\030\010 \001(\005\022\016\n\006status\030\t \001(\005B.\n\036com.vank" +
      "y.chat.common.protobufB\014BaseMsgProtob\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_vanky_chat_common_protobuf_BaseMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_vanky_chat_common_protobuf_BaseMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_vanky_chat_common_protobuf_BaseMsg_descriptor,
        new java.lang.String[] { "Id", "UniqueId", "FromUserId", "ToUserId", "CreateTime", "ChatType", "Content", "MsgType", "Status", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
